language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

os:
    - linux
    - osx
	
notifications:
  email:
    - info@AgilPhp.com
    - AgilPhp@gmail.com 
 
sudo: false

matrix:
    allow_failures:
        - php: 7.0

install: travis_retry composer install --no-interaction --prefer-source
