<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Ap | Login</title>

    <link href="<?PHP ECHO Ap_BASE_URL ?>/public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?PHP ECHO Ap_BASE_URL ?>/public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="<?PHP ECHO Ap_BASE_URL ?>/public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/css/animate.css" rel="stylesheet">
    <link href="<?PHP ECHO Ap_BASE_URL ?>/public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">Ap</h1>

            </div>

            <div>
            <h3>Login App</h3>
            </div>
            
            <form method="post" action="<?PHP ECHO Ap_BASE_URL ?>usuario/valida" class="m-t" role="form">
                <div class="form-group">
                    <input name="usuario" type="email" class="form-control" placeholder="Username" required="">
                </div>
                <div class="form-group">
                    <input name="clave"  type="password" class="form-control" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                <a href="#"><small>Forgot password?</small></a>
                <p class="text-muted text-center"><small>Do not have an account?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="<?PHP ECHO Ap_BASE_URL ?>usuario/registro">Create an account</a>
            </form>
            
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="<?PHP ECHO Ap_BASE_URL ?>/public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/jquery-2.1.1.js"></script>
    <script src="<?PHP ECHO Ap_BASE_URL ?>/public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/bootstrap.min.js"></script>

</body>

</html>